export const GEOGRAPHY_DATA = [
    { "village_name": "Akkurthy", "panchayati_name": "Akkurthy", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Penubaka", "panchayati_name": "Akkurthy", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ammapalem", "panchayati_name": "Ammapalem", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Chukkalanidigallu", "panchayati_name": "Ammapalem", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Aravakothuru", "panchayati_name": "Aravakothuru", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Bokkasam Palem", "panchayati_name": "Bokkasam Palem", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Brahmanapalle", "panchayati_name": "Brahmanapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Papanapalle", "panchayati_name": "Brahmanapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "BV Puram", "panchayati_name": "BV Puram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Gollapalle", "panchayati_name": "BV Puram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Murthy Palem", "panchayati_name": "BV Puram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Challapalem", "panchayati_name": "Chellapalem", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Cherlapalle", "panchayati_name": "Cherlapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Dommarapalem", "panchayati_name": "Dommarapalem", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Senagalumitta", "panchayati_name": "Dommarapalem", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Empedu", "panchayati_name": "Empedu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Erragudipadu", "panchayati_name": "Erragudipadu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Velavedu", "panchayati_name": "Gangalapudi", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Gangalapudi", "panchayati_name": "Gangalapudi", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Govindaraopalle", "panchayati_name": "Govindarau Palle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Anjaneya Puram", "panchayati_name": "Govindarau Palle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Mamidi Gunta", "panchayati_name": "Govindarau Palle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Madiri Palle", "panchayati_name": "Govindarau Palle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Guntakindapalle", "panchayati_name": "Guntakindapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Inagalur", "panchayati_name": "Inagalur", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Jaggarajupalli", "panchayati_name": "Jaggarajupalli", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kalavagunta", "panchayati_name": "Kalavagunta", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kammakothur", "panchayati_name": "Kammakothur", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kapugunneri", "panchayati_name": "Kapugunneri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "MMC Khandriga", "panchayati_name": "Kapugunneri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Isukagunta", "panchayati_name": "Kapugunneri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kodandaramapuram", "panchayati_name": "Kodandaramapuram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kothuru Chellamambapuram", "panchayati_name": "Kuntipudi", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kuntipudi", "panchayati_name": "Kuntipudi", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ramanuja Palle", "panchayati_name": "Kuntipudi", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Maddiledu", "panchayati_name": "Maddiledu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ananthapadmanabha Puram", "panchayati_name": "Mangalapuri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Mangalapuri", "panchayati_name": "Mangalapuri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Muddumudi", "panchayati_name": "Mangalapuri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Kothapalle Chinthala", "panchayati_name": "Mannavaram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Mannavaram", "panchayati_name": "Mannavaram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Melachur", "panchayati_name": "Melachur", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Bodavaripalle", "panchayati_name": "Muchivolu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Muchivolu", "panchayati_name": "Muchivolu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Narayanapuram", "panchayati_name": "Narayanapuram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Panagallu", "panchayati_name": "Narayanapuram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Jingilipalem", "panchayati_name": "Narayanapuram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Obulayapalle", "panchayati_name": "Obulayapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Reddipalle", "panchayati_name": "Obulayapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ammacheruvu", "panchayati_name": "Pathagunta", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Appalayagunta", "panchayati_name": "Pathagunta", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Mangalagunta", "panchayati_name": "Pathagunta", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Pathagunta", "panchayati_name": "Pathagunta", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Timmavaram", "panchayati_name": "Pathagunta", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Bheemavaram", "panchayati_name": "Poli", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Poli", "panchayati_name": "Poli", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Vampalle", "panchayati_name": "Poli", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Pullareddi Khandriga", "panchayati_name": "Pullareddi Khandriga", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Rachagunneri", "panchayati_name": "Rachagunneri", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ramalinga Puram", "panchayati_name": "Ramalinga Puram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ramanujapalle", "panchayati_name": "Ramanujapalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Ramapuram", "panchayati_name": "Ramapuram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Abbatlapalli", "panchayati_name": "Ramapuram", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "ErramReddypalli", "panchayati_name": "ReddyPalli", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Reddypalli", "panchayati_name": "ReddyPalli", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Renigunta", "panchayati_name": "Renigunta", "mandal_name": "Renigunta", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Sri Kalahasti", "panchayati_name": "Sri Kalahasti", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Subba Naidu Khandriga", "panchayati_name": "Subba Naidu Khandriga", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Suruvaripalle", "panchayati_name": "Suruvaripalle", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Thondamanadu", "panchayati_name": "Thondamanadu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Tottambedu", "panchayati_name": "Tottambedu", "mandal_name": "Tottambedu", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Udamalapadu", "panchayati_name": "Udamalapadu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Cherukulapadu", "panchayati_name": "Udamalapadu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Gopalakrishnapuram", "panchayati_name": "Udamalapadu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Uranduru", "panchayati_name": "Uranduru", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Yellampalle", "panchayati_name": "Vagavedu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Vagavedu", "panchayati_name": "Vagavedu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Endrapalle", "panchayati_name": "Vagavedu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Sahasralingeswara Puram", "panchayati_name": "Vedam", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Vedam", "panchayati_name": "Vedam", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Velampadu", "panchayati_name": "Velampadu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Madamala", "panchayati_name": "Velavedu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Velavedu", "panchayati_name": "Velavedu", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Yarlapudi", "panchayati_name": "Yarlapudi", "mandal_name": "Sri Kalahasti", "constituency_name": "Sri Kalahasti" },
    { "village_name": "Yerpedu", "panchayati_name": "Yerpedu", "mandal_name": "Yerpedu", "constituency_name": "Sri Kalahasti" }
];
